In [1]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import scipy
from PIL import Image
from scipy import ndimage
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.python.framework import ops
import os

%matplotlib inline
np.random.seed(1)
tf.compat.v1.disable_eager_execution()

In [2]:
image = Image.open('test/000e7aa6-100b-4c6b-9ff0-e7a8e53e4465_5L.png')
print(image.format)
print(image.size)
print(image.mode)
# show the image
print(image)

PNG
(128, 128)
L
<PIL.PngImagePlugin.PngImageFile image mode=L size=128x128 at 0x1E77A881130>


In [3]:
data = np.asarray(image)
print(data.shape)
print(data)
batches = []
Y = []
count = 0

(128, 128)
[[71 70 70 ... 53 54 55]
 [70 71 71 ... 51 53 54]
 [70 71 73 ... 47 49 50]
 ...
 [45 43 41 ... 65 66 67]
 [47 44 39 ... 62 65 66]
 [48 45 37 ... 61 64 65]]


In [4]:
length = -1
for root, dirs, files in os.walk('train'):
    batch = []
    y = []
    length = len(files)
    for i in range(length):
        if i != 0 and i % 1000 == 0:
            batches.append(np.array(batch))
            batch = []
            y = np.array(y)
            Y.append(y)
            y = []
        image = Image.open('train/' + files[i])
        data = np.asarray(image)
        data = data.reshape((data.shape[0], data.shape[1], 1))
        batch.append(data)
        val = int(files[i][-6])
        answer = [val]
        '''
        for j in range(6):
            if j == val:
                answer.append(1)
            else:
                answer.append(0)
        '''
        y.append(answer)
    Y.append(y)
    if len(batch) != 0:
        batches.append(batch)
print("Done")
print("No. of training examples:", length)

Done
No. of training examples: 18000


In [5]:
print(len(batches))
print(len(Y))
print(Y[0])

18
18
[[0]
 [0]
 [2]
 [0]
 [5]
 [5]
 [2]
 [2]
 [3]
 [0]
 [4]
 [2]
 [0]
 [1]
 [2]
 [3]
 [0]
 [3]
 [5]
 [5]
 [4]
 [0]
 [2]
 [2]
 [0]
 [5]
 [0]
 [0]
 [3]
 [3]
 [2]
 [1]
 [0]
 [0]
 [5]
 [4]
 [1]
 [0]
 [4]
 [4]
 [5]
 [1]
 [2]
 [2]
 [5]
 [3]
 [3]
 [4]
 [5]
 [3]
 [2]
 [2]
 [2]
 [2]
 [5]
 [0]
 [5]
 [5]
 [2]
 [2]
 [4]
 [3]
 [5]
 [0]
 [0]
 [4]
 [1]
 [0]
 [2]
 [0]
 [1]
 [5]
 [0]
 [4]
 [2]
 [3]
 [1]
 [0]
 [3]
 [2]
 [2]
 [0]
 [1]
 [0]
 [5]
 [1]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [5]
 [3]
 [4]
 [1]
 [0]
 [5]
 [2]
 [1]
 [5]
 [5]
 [5]
 [2]
 [4]
 [2]
 [4]
 [0]
 [2]
 [5]
 [3]
 [3]
 [1]
 [1]
 [1]
 [5]
 [1]
 [4]
 [4]
 [0]
 [4]
 [3]
 [2]
 [5]
 [2]
 [1]
 [2]
 [3]
 [2]
 [2]
 [1]
 [4]
 [5]
 [3]
 [1]
 [1]
 [4]
 [2]
 [5]
 [2]
 [0]
 [4]
 [1]
 [0]
 [1]
 [5]
 [2]
 [4]
 [2]
 [5]
 [4]
 [1]
 [3]
 [1]
 [2]
 [1]
 [0]
 [5]
 [4]
 [5]
 [0]
 [0]
 [0]
 [5]
 [1]
 [0]
 [1]
 [5]
 [4]
 [1]
 [0]
 [4]
 [2]
 [3]
 [5]
 [4]
 [0]
 [0]
 [5]
 [2]
 [3]
 [1]
 [3]
 [0]
 [0]
 [0]
 [0]
 [5]
 [1]
 [2]
 [4]
 [0]
 [4]
 [1]
 [3]
 [1]
 [2]
 [3]

In [6]:
print(batches[2][0].shape)
print(batches[2][0][0])

(128, 128, 1)
[[33]
 [38]
 [47]
 [49]
 [42]
 [39]
 [42]
 [45]
 [48]
 [47]
 [42]
 [42]
 [47]
 [50]
 [50]
 [50]
 [49]
 [49]
 [50]
 [52]
 [56]
 [55]
 [48]
 [45]
 [45]
 [46]
 [49]
 [48]
 [43]
 [40]
 [38]
 [40]
 [47]
 [47]
 [41]
 [41]
 [45]
 [46]
 [44]
 [44]
 [46]
 [44]
 [37]
 [36]
 [42]
 [44]
 [43]
 [42]
 [43]
 [45]
 [50]
 [53]
 [53]
 [50]
 [45]
 [41]
 [38]
 [37]
 [39]
 [42]
 [45]
 [46]
 [46]
 [45]
 [43]
 [41]
 [39]
 [38]
 [39]
 [41]
 [45]
 [46]
 [44]
 [40]
 [33]
 [32]
 [36]
 [40]
 [46]
 [46]
 [39]
 [34]
 [33]
 [33]
 [35]
 [41]
 [50]
 [53]
 [50]
 [49]
 [48]
 [46]
 [43]
 [43]
 [48]
 [50]
 [48]
 [45]
 [41]
 [38]
 [36]
 [36]
 [37]
 [36]
 [34]
 [34]
 [35]
 [38]
 [43]
 [43]
 [37]
 [37]
 [43]
 [43]
 [39]
 [37]
 [37]
 [37]
 [41]
 [41]
 [38]
 [34]
 [31]
 [28]
 [27]
 [25]
 [19]
 [17]]


In [12]:
inputs = layers.Input((128, 128, 1))
x = layers.Conv2D(3, 4, padding = 'same', activation = 'relu')(inputs)
x = layers.MaxPooling2D(pool_size = (3, 3))(x)
x = layers.Conv2D(32, 3, padding = 'valid', activation = 'relu')(x)
x = layers.MaxPooling2D(pool_size = (3, 3))(x)
x = layers.Conv2D(64, 3, padding = 'valid', activation = 'relu')(x)
x = layers.MaxPooling2D(pool_size = (2,2))(x)
x = layers.Flatten()(x)
x = layers.Dense(128, activation = 'relu')(x)
x = layers.Dense(64, activation = 'relu')(x)
x = layers.Dense(32, activation = 'relu')(x)
outputs = layers.Dense(6)(x)

model = keras.Model(inputs = inputs, outputs = outputs)

In [13]:
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits = True),
    optimizer = keras.optimizers.Adam(lr = 0.3),
    metrics = ['accuracy']
)

In [14]:
X_test = [i for i in batches[-1]]
Y_test = []
X_train = []
Y_train = []
print(len(Y))

for i in range(len(batches[:-1])):
    for j in batches[i]:
        X_train.append(j)
    
    for j in Y[i]:
        Y_train.append(j)

for i in Y[-1]:
    Y_test.append(i)
print(len(X_train))
X_train = np.array(X_train)
X_test = np.array(X_test)
Y_train = np.array(Y_train)
Y_test = np.array(Y_test)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

18
17000
(17000, 128, 128, 1)
(1000, 128, 128, 1)
(17000, 1)
(1000, 1)


In [15]:
print(model.summary())
for i in model.layers:
    print(i.output_shape)
model.fit(X_train, Y_train, batch_size = 1000, epochs = 10, verbose = 2)

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 128, 128, 1)]     0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 128, 128, 3)       51        
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 42, 42, 3)         0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 40, 40, 32)        896       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 5, 5, 64)          0   

In [16]:
model.evaluate(X_test, Y_test, batch_size = 1000, verbose = 2)

[1.792703628540039, 0.179]